Repository wecode-bootcamp-korea/12-Allstar-frontend, pull requests merged in 2020-09, with the labels that each got.

#3 [12기 문상호] Add: 메인 페이지 하단 marketing tile 추가
  public/data/Main/SHOESICONDATA.json
  public/images/Main/changeAndRefund.png
  public/images/Main/delivery.png
  public/images/Main/facebook.png
  public/images/Main/heart.jpg
  public/images/Main/insta.png
  public/images/Main/memberBenefit.png
  src/Pages/Main/Components/DashBoard1.js
  src/Pages/Main/Components/DashBoard1.scss
  src/Pages/Main/Components/DashBoard2.js
  src/Pages/Main/Components/DashBoard2.scss
  src/Pages/Main/Components/DashBoard3.js
  src/Pages/Main/Components/DashBoard3.scss
  src/Pages/Main/Components/DashBoard4.js
  src/Pages/Main/Components/DashBoard4.scss
  src/Pages/Main/Components/DashBoard5.js
  src/Pages/Main/Components/DashBoard5.scss
  src/Pages/Main/Components/MarketingTile.js
  src/Pages/Main/Components/MarketingTile.scss
  src/Pages/Main/Components/MediaTile1.js
  src/Pages/Main/Components/MediaTile1.scss
  src/Pages/Main/Components/MediaTile2.js
  src/Pages/Main/Components/MediaTile2.scss
  src/Pages/Main/Components/MediaTile3.js
  src/Pages/Main/Components/MediaTile3.scss
  src/Pages/Main/Components/ProductInfo.js
  src/Pages/Main/Components/ProductInfo.scss
  src/Pages/Main/Components/ShoesIconList.js
  src/Pages/Main/Components/ShoesIconList.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Styles/common.scss
Labels: Status: Accepted

#5 [12기 김호균] ADD: SASS 리뷰 반영 완료
  package-lock.json
  package.json
  src/Pages/Signup/SignUp.js
  src/Pages/Signup/SignUp.scss
  src/Routes.js
  src/index.js
Labels: Status: Accepted

#6 [12기 문상호] Refactor: 멘토 리뷰 반영 (불필요한 fragment 제거)
  public/images/Footer/facebook.png
  public/images/Footer/insta.png
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Routes.js
Labels: Status: Accepted

#4 [12기 권영빈]상품 상세페이지 레이아웃 (1차)
  public/data/ProductDetail/CommunityProductsMOCK.json
  public/data/ProductDetail/ProductDetailMOCK.json
  public/data/ProductDetail/RecommendMOCK.json
  public/images/productDetail/facebook_icon.png
  public/images/productDetail/kakao_icon.png
  public/images/productDetail/line_icon.png
  public/images/productDetail/minus_icon.png
  public/images/productDetail/plus_icon.png
  src/Components/SizeGuideModal/SizeFind.js
  src/Components/SizeGuideModal/SizeFind.scss
  src/Components/SizeGuideModal/SizeGuide.js
  src/Components/SizeGuideModal/SizeGuidePanel.scss
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/Pages/ProductDetail/ProductDetailFeed/ProductCommunity.js
  src/Pages/ProductDetail/ProductDetailFeed/ProductCommunity.scss
  src/Pages/ProductDetail/ProductDetailFeed/ProductDetailFeed.js
  src/Pages/ProductDetail/ProductDetailFeed/ProductDetailFeed.scss
  src/Pages/ProductDetail/ProductDetailFeed/ProductDetailImg.js
  src/Pages/ProductDetail/ProductDetailFeed/ProductDetailImg.scss
  src/Pages/ProductDetail/ProductDetailFeed/ProductInfo.js
  src/Pages/ProductDetail/ProductDetailFeed/ProductInfo.scss
  src/Pages/ProductDetail/ProductDetailFeed/ProductMainImg.js
  src/Pages/ProductDetail/ProductDetailFeed/ProductMainImg.scss
  src/Pages/ProductDetail/ProductDetailFeed/ProductReview.js
  src/Pages/ProductDetail/ProductDetailFeed/ProductReview.scss
  src/Pages/ProductDetail/ProductDetailRecommend/ProductDetailRecommend.js
  src/Pages/ProductDetail/ProductDetailRecommend/ProductDetailRecommend.scss
  src/Pages/ProductDetail/ProductDetailRight/ProductDetailRight.js
  src/Pages/ProductDetail/ProductDetailRight/ProductDetailRight.scss
  src/Pages/ProductDetail/ProductDetailRight/ProductRightColor.js
  src/Pages/ProductDetail/ProductDetailRight/ProductRightColor.scss
  src/Pages/ProductDetail/ProductDetailRight/ProductRightEtc.js
  src/Pages/ProductDetail/ProductDetailRight/ProductRightEtc.scss
  src/Pages/ProductDetail/ProductDetailRight/ProductRightSize.js
  src/Pages/ProductDetail/ProductDetailRight/ProductRightSize.scss
  src/Pages/ProductDetail/ProductDetailRight/ProductRightSummary.js
  src/Pages/ProductDetail/ProductDetailRight/ProductRightSummary.scss
  src/Routes.js
Labels: Status: Accepted

#8 [12기 문상호] Add: Main.js에 Footer Component 삽입
  package-lock.json
  package.json
  src/Components/Footer/Footer.scss
  src/Pages/Main/Components/DashBoard1.scss
  src/Pages/Main/Components/DashBoard2.scss
  src/Pages/Main/Components/DashBoard3.scss
  src/Pages/Main/Components/DashBoard4.scss
  src/Pages/Main/Components/DashBoard5.scss
  src/Pages/Main/Components/MediaTile1.scss
  src/Pages/Main/Components/MediaTile2.scss
  src/Pages/Main/Components/MediaTile3.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/index.js
Labels: Status: Accepted

#7 [12기 문상호] Add: Main.js에 Promotion Banner Slider 추가
  package-lock.json
  package.json
  src/Components/PromoBanner/PromoBanner.js
  src/Components/PromoBanner/PromoBanner.scss
  src/Components/PromoBanner/SliderContent.js
  src/Components/PromoBanner/SliderContent.scss
  src/Pages/Main/Main.js
  src/Routes.js
Labels: Status: Accepted

#10 [12기 권영빈] 상품 상세페이지 기능 추가 (2차)
  src/Components/SizeGuideModal/SizeFind.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/Pages/ProductDetail/ProductDetailRecommend/ProductDetailRecommend.scss
  src/Pages/ProductDetail/ProductDetailRight/ProductRightSize.js
  src/Pages/ProductDetail/ProductDetailRight/ProductRightSize.scss
  src/Routes.js
Labels: Status: 추가 기능 구현중

#2 [12기 손병진]상품리스트 레이아웃 및 기능 구현_3차
  public/data/ProductList/Products copy.json
  public/data/ProductList/Products.json
  public/images/productList/filter.png
  public/images/productList/heart_fill.png
  public/images/productList/preloader.gif
  src/Pages/ProductList/Components/FilterHorizontalBar/FilterHorizontalBar.js
  src/Pages/ProductList/Components/FilterHorizontalBar/FilterHorizontalBar.scss
  src/Pages/ProductList/Components/FilterVerticalBar/FilterComponents/FilterColor/FilterColor.js
  src/Pages/ProductList/Components/FilterVerticalBar/FilterComponents/FilterColor/FilterColor.scss
  src/Pages/ProductList/Components/FilterVerticalBar/FilterComponents/FilterGender/FilterGender.js
  src/Pages/ProductList/Components/FilterVerticalBar/FilterComponents/FilterGender/FilterGender.scss
  src/Pages/ProductList/Components/FilterVerticalBar/FilterComponents/FilterSilluet/FilterSilluet.js
  src/Pages/ProductList/Components/FilterVerticalBar/FilterComponents/FilterSilluet/FilterSilluet.scss
  src/Pages/ProductList/Components/FilterVerticalBar/FilterComponents/FilterSize/FilterSize.js
  src/Pages/ProductList/Components/FilterVerticalBar/FilterComponents/FilterSize/FilterSize.scss
  src/Pages/ProductList/Components/FilterVerticalBar/FilterComponents/FilterType/FilterType.js
  src/Pages/ProductList/Components/FilterVerticalBar/FilterComponents/FilterType/FilterType.scss
  src/Pages/ProductList/Components/FilterVerticalBar/FilterVerticalBar.js
  src/Pages/ProductList/Components/FilterVerticalBar/FilterVerticalBar.scss
  src/Pages/ProductList/Components/FilterVerticalBar/filterContents.js
  src/Pages/ProductList/Components/ProductContainer/ProductColors/ProductColors.js
  src/Pages/ProductList/Components/ProductContainer/ProductColors/ProductColors.scss
  src/Pages/ProductList/Components/ProductContainer/ProductContainer.js
  src/Pages/ProductList/Components/ProductContainer/ProductContainer.scss
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#14 [12기 손병진] 상품리스트 중간발표 자료
  src/Components/Nav/Nav.scss
  src/Pages/ProductList/Components/ProductContainer/ProductColors/ProductColors.scss
  src/Pages/ProductList/Components/ProductContainer/ProductContainer.js
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/Pages/SignUp/SignUp.scss
Labels: Status: Accepted

#15 [12기 김호균] 로그인 로그아웃 기능추가구현 완성
  src/Components/Nav/Nav.scss
  src/Pages/Login/Login.js
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
Labels: Status: 리뷰 요청
